// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'

export const createDocumentRequestSchema = z.object({
  collectionId: z.string(),
  name: z.string(),
  path: z.string(),
  type: z.string(),
  instructions: z.string().optional(),
  job: z.boolean().optional(),
  tables: z.boolean().optional()
})

export const createDocumentResponseSchema = baseResponseSchema.extend({
  id: z.string()
})
