// Generated by ts-to-zod
import { z } from 'zod'
import {
  audioLayoutSchema,
  documentLayoutSchema,
  photoLayoutSchema,
  videoLayoutSchema
} from '../layout.zod'

export const exportDocumentRequestSchema = z.object({
  collectionId: z.string(),
  documentId: z.string(),
  type: z.union([z.literal('json'), z.literal('text')]).optional()
})

export const exportDocumentResponseSchema = z.union([
  z.array(documentLayoutSchema),
  z.array(audioLayoutSchema),
  z.array(photoLayoutSchema),
  z.array(videoLayoutSchema),
  z.string()
])
