// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'
import { documentSchema } from '../document.zod'

export const getDocumentRequestSchema = z.object({
  collectionId: z.string(),
  documentId: z.string()
})

export const getDocumentResponseSchema = baseResponseSchema.extend({
  result: documentSchema.nullable()
})
