// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'
import { documentSchema } from '../document.zod'
import { jobStatusSchema } from '../job.zod'

export const getDocumentsRequestSchema = z.object({
  collectionId: z.string(),
  search: z.string().optional(),
  take: z.number().optional(),
  skip: z.number().optional(),
  extended: z.boolean().optional(),
  status: jobStatusSchema.optional(),
  nodes: jobStatusSchema.optional(),
  edges: jobStatusSchema.optional(),
  vectors: jobStatusSchema.optional(),
  category: jobStatusSchema.optional()
})

export const getDocumentsResponseSchema = baseResponseSchema.extend({
  result: z.array(documentSchema)
})
