// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'
import { jobTypeSchema } from '../job.zod'

export const reprocessDocumentsRequestSchema = z.object({
  collectionId: z.string(),
  ids: z.array(z.string()),
  type: jobTypeSchema
})

export const reprocessDocumentsResponseSchema = baseResponseSchema
