// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'

export const updateDocumentRequestSchema = z.object({
  collectionId: z.string(),
  documentId: z.string(),
  name: z.string().optional(),
  instructions: z.string().optional(),
  tables: z.boolean().optional(),
  job: z.boolean().optional()
})

export const updateDocumentResponseSchema = baseResponseSchema
