// Generated by ts-to-zod
import { z } from 'zod'

/**
 * Valid status values for API responses.
 */
export const statusTypeSchema = z.union([z.literal('OK'), z.literal('ERROR')])

/**
 * Common fields included with every API request.
 */
export const baseRequestSchema = z.object({
  apiKey: z.string().describe('API key used for request authentication.'),
  apiUrl: z.string().describe('Base URL of the Gestell API endpoint.'),
  debug: z.boolean().describe('Flag to enable verbose logging for debugging.')
})

/**
 * Common fields returned with every API response.
 */
export const baseResponseSchema = z.object({
  status: statusTypeSchema.describe(
    'Indicates whether the request succeeded or failed.'
  ),
  message: z
    .string()
    .optional()
    .describe(
      'Optional human-readable message with additional information or error details.'
    )
})
