// Generated by ts-to-zod
import { z } from 'zod'
import { jobSchema } from './job.zod'
import {
  audioLayoutSchema,
  documentLayoutSchema,
  layoutTypeSchema,
  photoLayoutSchema,
  videoLayoutSchema
} from './layout.zod'

export const documentSchema = z.object({
  id: z.string(),
  collectionId: z.string(),
  name: z.string(),
  type: z.string(),
  layoutType: layoutTypeSchema,
  layoutNodes: z.number(),
  tables: z.boolean(),
  instructions: z.string(),
  job: jobSchema.optional(),
  layout: z
    .union([
      z.array(documentLayoutSchema),
      z.array(photoLayoutSchema),
      z.array(videoLayoutSchema),
      z.array(audioLayoutSchema)
    ])
    .optional(),
  metadata: z
    .object({
      size: z.number(),
      pages: z.number(),
      length: z.number()
    })
    .optional(),
  dateCreated: z.date(),
  dateUpdated: z.date()
})
