// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'
import { featureLayoutSchema } from '../layout.zod'

export const featuresQueryRequestSchema = z.object({
  collectionId: z.string(),
  categoryId: z.string(),
  take: z.number().optional(),
  skip: z.number().optional()
})

export const featuresQueryResponseSchema = baseResponseSchema.extend({
  result: z.array(featureLayoutSchema)
})
