// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'

export const tablesQueryRequestSchema = z.object({
  collectionId: z.string(),
  categoryId: z.string(),
  skip: z.number().optional(),
  take: z.number().optional(),
  prompt: z.string().optional()
})

export const tablesQueryResponseSchema = baseResponseSchema.extend({
  result: z.array(z.record(z.string()))
})
