// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'

export const exportTableRequestSchema = z.object({
  collectionId: z.string(),
  categoryId: z.string(),
  format: z.union([z.literal('json'), z.literal('csv')]).optional(),
  take: z.number().optional(),
  skip: z.number().optional()
})

export const exportTableResponseSchema = baseResponseSchema.extend({
  result: z.union([z.array(z.record(z.string())), z.string()])
})
