// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'
import { searchResultSchema } from '../query.zod'

export const searchQueryResponseSchema = baseResponseSchema.extend({
  result: z.array(searchResultSchema)
})

export const promptQueryResponseSchema = z.string()
