// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'
import { organizationResultSchema } from '../organization.zod'

export const getOrganizationRequestSchema = z.object({
  id: z.string()
})

export const getOrganizationResponseSchema = baseResponseSchema.extend({
  result: organizationResultSchema.nullable()
})
