// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'
import { organizationListResultSchema } from '../organization.zod'

export const getOrganizationsRequestSchema = z.object({
  search: z.string().optional(),
  take: z.number().optional(),
  skip: z.number().optional(),
  extended: z.boolean().optional()
})

export const getOrganizationsResponseSchema = baseResponseSchema.extend({
  result: z.array(organizationListResultSchema)
})
