// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'
import {
  collectionTypeSchema,
  createCategoryPayloadSchema,
  piiIdentifierOptionSchema
} from '../collection.zod'

export const createCollectionRequestSchema = z.object({
  organizationId: z.string(),
  name: z.string(),
  type: collectionTypeSchema,
  tags: z.array(z.string()).optional(),
  description: z.string().optional(),
  pii: z.boolean().optional(),
  piiControls: z.array(piiIdentifierOptionSchema).optional(),
  instructions: z.string().optional(),
  graphInstructions: z.string().optional(),
  promptInstructions: z.string().optional(),
  searchInstructions: z.string().optional(),
  categories: z.array(createCategoryPayloadSchema).optional()
})

export const createCollectionResponseSchema = baseResponseSchema.extend({
  id: z.string()
})
