// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'
import { collectionSchema } from '../collection.zod'

export const getCollectionsRequestSchema = z.object({
  search: z.string().optional(),
  take: z.number().optional(),
  skip: z.number().optional(),
  extended: z.boolean().optional()
})

export const getCollectionsResponseSchema = baseResponseSchema.extend({
  result: z.array(collectionSchema)
})
