// Generated by ts-to-zod
import { z } from 'zod'
import { baseResponseSchema } from '../base.zod'
import {
  collectionTypeSchema,
  piiIdentifierOptionSchema
} from '../collection.zod'

export const updateCollectionRequestSchema = z.object({
  collectionId: z.string(),
  organizationId: z.string().optional(),
  name: z.string().optional(),
  type: collectionTypeSchema.optional(),
  description: z.string().optional(),
  pii: z.boolean().optional(),
  piiControls: z.array(piiIdentifierOptionSchema).optional(),
  instructions: z.string().optional(),
  graphInstructions: z.string().optional(),
  promptInstructions: z.string().optional(),
  searchInstructions: z.string().optional(),
  tags: z.array(z.string()).optional()
})

export const updateCollectionResponseSchema = baseResponseSchema
